### ISSUE TITLE
Please make it more clear that some fields are there to search for specific entities and can't be used as a drop-down.

### ISSUE THREAD

**Issue by subwaystation** [qbicsoftware/data-manager-app#615]
Hi there, both in Firefox and Chromium I am stuck at `4 Experimental Information`. 
The drop-down lists for Species, Specimen, Analytes do not appear even when I frantically click on them. But they are mandatory.

Best,
Simon

PS: A screenshot of where I got stuck:

![Screenshot from 2024-06-12 13-52-07](https://github.com/qbicsoftware/data-manager-app/assets/10184961/f3d488b1-49a0-4354-8b2d-4e5c7d4db4e5)

**Comment by subwaystation** [comment]
HAHAHAHHA

ok I didn't realize this is a search field, LUL

maybe this can be improved
just by accident I found out to enter some text in there to get what I want

**Comment by subwaystation** [comment]
you are right, I totally overlooked this
in my mind, a drop-down menu always suggests something, but maybe it's only me

anyhow, maybe add a lense somewhere so it is clearer it is a search?

**Comment by sven1103** [comment]
fixed in #632
