### ISSUE TITLE
Please cache project creation progress

### ISSUE THREAD

**Issue by subwaystation** [qbicsoftware/data-manager-app#616]
When I am in the middle of creating a project and I accidentally press ESC, I have to restart the whole process again. None of my information already entered is saved.

**Comment by sven1103** [comment]
Dear @subwaystation , 

can you explain, what has lead to the accidental ESC button interaction? The ESC is default behaviour to escape any current action, so we assume users want to abort.

**Comment by subwaystation** [comment]
I agree that I want to abort the current window (aka creating a new project), but in my flow at the time of testing, I was hoping I could continue at this state.

alternatively, you could provide a button: continue project (for the last unfinished one)

**Comment by sven1103** [comment]
Dear @subwaystation, 

can you elaborate, why you left the registration process and wanted to continue later? Have you been unsure about the experimental setup? 

We would like to understand your workflow better, to see if that is an important use case.

The accidental ESC action can be addressed by the implementation of  an additional confirmation modal.

**Comment by sven1103** [comment]
We track down the abort confirmation modal, but are currently not planning to implement a project creation cache. The creation of a project is quick once you have the required information.
