### ISSUE TITLE
the app claims project QBERT already exists, but when I search for it on the HOME page, it does not appear

### ISSUE THREAD

**Issue by subwaystation** [qbicsoftware/data-manager-app#617]
the app claims project QBERT already exists, but when I search for it on the HOME page, it does not appear

So what to do?

**Comment by subwaystation** [comment]
![Screenshot from 2024-06-12 14-03-29](https://github.com/qbicsoftware/data-manager-app/assets/10184961/b7a7ff62-8f0e-4e25-b49b-0b8c5096ed2b)

**Comment by subwaystation** [comment]
again the same problem, but this time with QWERT as a manually selected name
also I didn't select this name before, so it should work, the project can't exist, yet

![image](https://github.com/qbicsoftware/data-manager-app/assets/10184961/3b75a1e6-c807-448c-b6d8-037af84ceca4)

**Comment by subwaystation** [comment]
it seems this is happening even for automate generated codes

![image](https://github.com/qbicsoftware/data-manager-app/assets/10184961/85a8809d-553a-4eaa-9195-695224810f42)

**Comment by sven1103** [comment]
Thank you @wow-such-code , we are looking into the issue asap and will come back to you for more details.

**Comment by subwaystation** [comment]
:hot:

**Comment by KochTobi** [comment]
Hi @subwaystation 
The issue is fixed so I close this issue.
