### ISSUE TITLE
 `please provide a name` appears 2 times when selecting a PI

### ISSUE THREAD

**Issue by subwaystation** [qbicsoftware/data-manager-app#619]
![Uploading Screenshot from 2024-06-12 14-23-31.png…]()

**Comment by sven1103** [comment]
Dear @subwaystation , we cannot see any screenshot, do you mind posting it again please? Guess you have been faster creating the issue then the upload ;)

**Comment by subwaystation** [comment]
lol

**Comment by subwaystation** [comment]
![Screenshot from 2024-06-12 14-23-31](https://github.com/qbicsoftware/data-manager-app/assets/10184961/85cd85fb-375a-4d4b-98e2-17de832f93ec)

**Comment by subwaystation** [comment]
there u go

**Comment by KochTobi** [comment]
Hi @subwaystation 
The issue will be fixed in the next release. Thank you for reporting the bug.
