### ISSUE TITLE
Improve experimental groups visualisation for complex setups

### ISSUE THREAD

**Issue by sven1103** [qbicsoftware/data-manager-app#673]
**Is your feature request related to a problem? Please describe.**
When having many groups the visualisation was not easy to see, I had one row (over 2 screens) with many imaginary combinations (3 columns, 2x3x3 factors, e.g. 2 treatments, 3 timepoints, 3 genotypes/environments). But maybe 2x3x3 is too much anyway for that view.

**Describe the solution you'd like**
Maybe would be nice to have in several rows (to scroll down instead of to the right

**Comment by sven1103** [comment]
Issue was reported by @d4straub

**Comment by Shraddha0903** [comment]
Already covered by issue #744
