### ISSUE TITLE
Improve "Prefill Spreadsheat" feature to account for more permuations

### ISSUE THREAD

**Issue by sven1103** [qbicsoftware/data-manager-app#674]
**Is your feature request related to a problem? Please describe.**
Not all permutations are currently considered when registering a sample batch in case of multiple analytes present.

**Describe the solution you'd like**
Might be nice to have permutations also with analytes, that seem to be not considered right now (my imaginary example had DNA & RNA, and I wanted DNA and RNA analyzed for each sample

**Comment by sven1103** [comment]
Issue was reported by @d4straub

**Comment by d4straub** [comment]
Just asking because that was closed automatically (apologies, no idea of your workflows): Is that not happening any more or was it implemented already? Doesnt seem obvious to me.
