### ISSUE TITLE
Move from the spreadsheet component for sample batch registration to .XLSX upload

### ISSUE THREAD

**Issue by Shraddha0903** [qbicsoftware/data-manager-app#680]
**Is your feature request related to a problem? Please describe.**
The spreadsheet component has proven to be less usable after some user testing since it has limited functionality as compared to excel sheets and is cumbersome to maintain.

**Describe the solution you'd like**
Measurement registration via .XLSX sheet upload is tested to be a rather easy-to-use and preferred way of metadata handling. It can also be extended for registering sample metadata.

**Comment by spisthename** [comment]
Suggestion:

![Image](https://github.com/user-attachments/assets/f6a62d9c-3eea-4915-ba56-af5e2c2586c4)
![Image](https://github.com/user-attachments/assets/05409a6d-6575-481b-9d02-ff31485fd1aa)
![Image](https://github.com/user-attachments/assets/26b35d22-d188-4696-98cc-5c49baacc92d)
![Image](https://github.com/user-attachments/assets/dee9ff0d-ebb2-4f6a-aff6-67de8be8cb30)
![Image](https://github.com/user-attachments/assets/73a93309-5ab3-4f18-b5fb-7b71518d2d55)

**Comment by Shraddha0903** [comment]
Suggestions:

Sample Registration Flow Mockups:

![Image](https://github.com/user-attachments/assets/f4792ede-58ac-440f-9408-5cd9556bddbc)

![Image](https://github.com/user-attachments/assets/8a01af16-2fba-4344-9a71-1ceb5be794b2)

![Image](https://github.com/user-attachments/assets/b6abb32a-ae0f-4965-b6df-c21b8c5f2d67)

![Image](https://github.com/user-attachments/assets/4ff86642-b00d-468d-b043-4546f086eabb)

![Image](https://github.com/user-attachments/assets/bb41fcb5-4b68-425f-b5c3-653aeb6de3e1)

**Comment by KochTobi** [comment]
Hi @Shraddha0903 
I am missing where the user decides whether the sample batch is a pilot or not. I will introduce a checkbox now next to the batch name.

**Comment by KochTobi** [comment]
Code is done. Waiting on documentation to be finished.
