### ISSUE TITLE
Provide a notification based feedback system 

### ISSUE THREAD

**Issue by Steffengreiner** [qbicsoftware/data-manager-app#682]
**Is your feature request related to a problem? Please describe.**
Currently the users are not informed in a harmonized way. Notifications are shown sometimes on top and on the bottom left. This concerns the following notifications (Thanks SP for collecting):

**Success notifications (Toasts)**

Usage: Triggered after successful completion of each task

**Warning notifications (Dialogs)**

Usage: To warn the user of potential risks that may arise during an interaction. 

**Information notifications (Dialogs)**

Confirmation msg on dialog cancellation 

**Error Notifications**

Usage: To inform users of critical issues and guide them to resolution.

**Describe the solution you'd like**
Notifications are shown as "toast" notifications with a clear warning/error/success indication instead of stacking on top of each other

**Describe alternatives you've considered**
There is no alternative! 

**Additional context**
To see an example: This is already done after experimental group registration to guide the user to the sample registration.

**Comment by KochTobi** [comment]
There is no alternative? I do not believe that. What alternatives did you consider and why did you decide for the proposed solution?

**Comment by Steffengreiner** [comment]
Heya @KochTobi, 

The proposed solution is in adherence to the design made by @Shraddha0903, which is why i did not propose an alternative. 
Basically there is a need to harmonize how users are informed in the application, which is not streamlined at the moment.

**Comment by Shraddha0903** [comment]
Thanks @Steffengreiner. @KochTobi as Steffen mentioned, this is just a task to have the notifications extended throughout the application. Currently it is not applied for all scenarios.
Also, I would like to clarify that we use toast notifications only for success/feedback msgs. For errors and warnings we use the dialog style as they are more critical. We do not use toast notifications for warnings/errors.

**Comment by KochTobi** [comment]
Some link to the notification system documentation (can be javadocs) needs to be provided to complete this task. 

It is not part of this task to show the notifications everywhere.

**Comment by sven1103** [comment]
@Shraddha0903 please provide screenshots for the notification toast to look like, I cant review the PR #790

**Comment by sven1103** [comment]
@Shraddha0903 what is a sensitive value for the duration of a toast? I think 5 seconds is a little bit short, especially if the toast offers actionable items, like a link.

We might need to distinguish simple information and interactive toasts, whereas we might need different display duration settings.

**Comment by sven1103** [comment]
moved detailed to do list to #799

**Comment by Shraddha0903** [comment]
> @Shraddha0903 what is a sensitive value for the duration of a toast? I think 5 seconds is a little bit short, especially if the toast offers actionable items, like a link.
> 
> We might need to distinguish simple information and interactive toasts, whereas we might need different display duration settings.

Yes, agree. We can keep 5 seconds for the informational ones and 10 for the interactive ones.

**Comment by KochTobi** [comment]
> > [@Shraddha0903](https://github.com/Shraddha0903) what is a sensitive value for the duration of a toast? I think 5 seconds is a little bit short, especially if the toast offers actionable items, like a link.
> > We might need to distinguish simple information and interactive toasts, whereas we might need different display duration settings.
> 
> Yes, agree. We can keep 5 seconds for the informational ones and 10 for the interactive ones.

I adapted this. 5 seconds were chosen as recommended by vaadin https://vaadin.com/docs/latest/components/notification#duration
