### ISSUE TITLE
Inform user on reason for password invalidity during password reset

### ISSUE THREAD

**Issue by Steffengreiner** [qbicsoftware/data-manager-app#703]
**Describe the bug**
If an invalid password is provided as a to be set password during password reset the user is shown a general exception instead of being informed on why the provided password is invalid. 

**To Reproduce**
1. Progress the password reset process until a new password can be specified. 
2. In this New Password screen input a  password string that is invalid (e.g. due to length being too short) 
3. The data manager application will show a general exception error message instead of specifying to the user why the provided password is invalid.

**Expected behavior**
The user is informed about the reason why the provided password is too short instead of being shown a general application error. Ideally below the password setting textfield similiar to how it's done during user registration. 

**Screenshots**
<img width="1433" alt="Screenshot 2024-07-10 at 16 28 16" src="https://github.com/qbicsoftware/data-manager-app/assets/29627977/ba079664-3743-44f5-a4da-12a759ca9b8d">

**Desktop (please complete the following information):**
 - MacOs Sonoma 14.5 
 - Firefox 127.0.2 (64-Bit)
- Build on qpylon/dev

**Comment by KochTobi** [comment]
In the new password layout no validation takes place. Compare the field in the registration layout. The same validation should take place.
