### ISSUE TITLE
Possibility to download the project information

### ISSUE THREAD

**Issue by oquendoM** [qbicsoftware/data-manager-app#720]
Hello!

**Is your feature request related to a problem? Please describe.**
In some of the downstream analysis reports we need to provide project information, like project title, PI and contact at QBiC. At the moment there is no possibility to download this data from the Data Manager in a table format.

**Describe the solution you'd like**
I would like to have a feature like the **User Database - Download Project Information** that we currently have in the qPortal.

**Describe alternatives you've considered**
Manually copy and paste the information on tables, however this is very cumbersome.

**Comment by sven1103** [comment]
Dear @oquendoM 

so what you are looking for is a way to download a project information summary? 

Could you list the properties you would need for it to be contained?

Why do you favor a tabular format over e.g. a simple text file or YAML?

**Comment by oquendoM** [comment]
Hi @sven1103

Yes, we would like to have a way to automatically download the project information. Tagging @qbicStefanC here also.

Based on what is showed in the Project Summary page we would like:
- Project ID
- Title
- Objective
- Project collaborators

The pipeline uses a .tsv file as input. But from my test it also work with .txt if the arguments are separated by tab.

If the download is from within the Data Manager, I would expect the button to be next to "Edit" in the Project Summary page.

**Comment by sven1103** [comment]
Hi @oquendoM , 

Can you tell us more about the pipeline use case? I would favor (in order for standardization and interoperability) to implement standards more in the data manager, meaning an export e.g. in the domain standard format ISA (https://isa-specs.readthedocs.io/en/latest/isamodel.html#). 

Of course an proprietary format export is always an option, when a suiting standard is not available. 

Best, Sven

**Comment by sven1103** [comment]
After some personal discussion with @oquendoM and others, we settle on a JSON-based export format where the application provides the schema for it. 

Looking into existing standards and notations, I am suggesting to start with a JSON-LD export of a https://schema.org/ResearchProject object and decorate it e.g. for project manager, project contact and principal investigator. For the latter we can use https://schema.org/ContactPoint, which provides the properties we have.

**Comment by sven1103** [comment]
BTW, there is no need for JSON-LD libaries in Java, lets just annotate our export object classes properly, to adhere to JSON-LD:
https://json-ld.org/

Here is an example how to build it with jackson, no need to include yet another third party library:

https://stackoverflow.com/questions/50738973/jackson-jsonld-nested-objects
