### ISSUE TITLE
View ORCID in user profile

### ISSUE THREAD

**Issue by sven1103** [qbicsoftware/data-manager-app#733]
**Is your feature request related to a problem? Please describe.**
If my data manager account is already connected with an ORCID, I want to see it in my user profile overview.

**Describe the solution you'd like**
A visual indication that on ORCID is connected to the account, as well as the ORCID itself as confirmation.

**Comment by sven1103** [comment]
Ok, this task should be pretty straight forward to implement. @Shraddha0903 this would need a UI suggestion here.

Maybe sth that indicates that the user account is linked / connected to ORCID

**Comment by Shraddha0903** [comment]
Suggestion:

![Image](https://github.com/user-attachments/assets/749bd867-2cc9-4a07-98eb-f1aa5531d9a8)
