### ISSUE TITLE
Add information on how to enter experimental variables

### ISSUE THREAD

**Issue by KochTobi** [qbicsoftware/data-manager-app#738]
**Is your feature request related to a problem? Please describe.**
As a person working in the lab, when I want to enter experimental variables, I do not know how enter multiple levels.

**Describe the solution you'd like**
Describe somewhere that each row is one level or help me out here.

**Describe alternatives you've considered**
Provide multiple fields where I can enter experimental variables.
Provide an option for me to decide how to split my input.

**Additional context**
Adding levels with a list like `one, two, three` leads only to one level in the variable.

**Comment by Shraddha0903** [comment]
Suggestion: 
We provide example placeholders for each term in the Add Experimental Variables dialog and also provide helper text to the Levels text field so along with the example it is clear to the user. 


![Image](https://github.com/user-attachments/assets/a7c3b432-5131-4974-99fd-fac32136023f)
