### ISSUE TITLE
I cannot edit my measurements

### ISSUE THREAD

**Issue by KochTobi** [qbicsoftware/data-manager-app#739]
**Describe the bug**

**To Reproduce**
1. Download template
2. add measurement information
3. register measurement using the filled out template
4. edit information in the excel
5. upload the excel 
6. error unknown measurement id

**Expected behavior**
I can upload my original excel. Otherwise I need to have multiple excel file on my computer. This confuses me and is additional work I do not think is necessary.
Alternatively let me know that I uploaded/and probably edited the wrong file.

**Additional context**
I use a local excel file to have an overview over my measurements and the steps in my experiment. I want to upload that file instead of always copying information to a new file.

**Comment by sven1103** [comment]
I dont understand this issue. What is meant by "I can upload my original excel"?

**Comment by KochTobi** [comment]
The users download the template for measurement registration, fill it out and keep it on their computer. When they want to edit a measurement they change the information in this file and try to upload it resulting in errors as there is no measurement code, columns are different.
As lab people are used to keep track of measurement and processes in excel, this occurs frequently.

**Comment by sven1103** [comment]
But how should this work, if the measurement ID is not present?
