### ISSUE TITLE
When having a lot of experimental variables in an experiment I have to scroll to the right

### ISSUE THREAD

**Issue by KochTobi** [qbicsoftware/data-manager-app#743]
**Describe the bug**
When adding a lot of experimental variables I have to scroll to the right to see all of them. 

**To Reproduce**
1. Add a lot (>15) experimental variables
2. You have to scroll to the right

**Expected behavior**
The variables are in multiple rows.

**Screenshots**
![Screenshot 2024-07-29 at 16 02 29](https://github.com/user-attachments/assets/af223a00-e51a-48e3-acac-723a27e4ccb7)

**Smartphone (please complete the following information):**
 - Version data manager 1.2.3

**Comment by KochTobi** [comment]
does not work for 
Firefox 129.0.2

**Comment by sven1103** [comment]
@Steffengreiner this issue does not reference a PR, but has the status "Needs Review". Please link the PR that addresses the issue.

**Comment by Steffengreiner** [comment]
Dear @sven1103. my apologies, These cards are a remnant of the discussion i had with @Shraddha0903. 
The original issue was already addressed in an older PR, however the cards resizing themselves had to be fixed.  
I linked the relevant PR
