### ISSUE TITLE
Add project identifier to downloaded files

### ISSUE THREAD

**Issue by KochTobi** [qbicsoftware/data-manager-app#745]
**Is your feature request related to a problem? Please describe.**
When downloading the following files for multiple projects, I get confused as they are called the same.

- [x] download urls file in `Download Raw Data`
- [x] download measurement metdata file ngs in `View Measurements`
- [x] download measurement metadta file proteomics in `View Measurements`
- [x] download sample metadata in `Register Sample Batch`

**Describe the solution you'd like**
Simply prefix the file names with the project so I know for which projects they were downloaded.

**Comment by sven1103** [comment]
Note: exludes template files. Only project specific information files must have the project ID as prefix.

Should be straight forward to implement.
