### ISSUE TITLE
Please add `technical replicate` to proteomics measurement metadata

### ISSUE THREAD

**Issue by KochTobi** [qbicsoftware/data-manager-app#747]
**Is your feature request related to a problem? Please describe.**
As the proteomics labs switched their process and do always do technical replicates now, we want this information in the measurement metadata. The technical replicate column can be optional and freetext but should be one of the first columns so measurements can easily be identified. 

**Describe the solution you'd like**
Add technical replicates to the proteomics measurement metadata.

**Describe alternatives you've considered**
Add information on technical replicates to the comment column. As this column is one of the last columns, it is not very helpful if I want to identify my measurement as a lab person.

**Comment by sven1103** [comment]
@FraBarSol 
Before we can consider this issue, can you tell us how you would expect handling of technical metadata for sample pools?

**Comment by sven1103** [comment]
Ok, so together with @oquendoM , @FraBarSol , @Shraddha0903 , 

we agree to include it as simple property for measurement and in the case of samples, we agree to regard the future biological replicate property with equal names and conditions as technical replicate.

see also #735
