### ISSUE TITLE
Delete Session Cookies on Session Invalidation

### ISSUE THREAD

**Issue by wow-such-code** [qbicsoftware/data-manager-app#749]
The HA proxy functions on the session cookie. As vaadin updates the cookie content but not recreates the cookie itself, the draining does not work currently. Only expired cookies lead to a switch away from a drained node.

Is there a way to delete the cookie and re-create it instead of changing its contents?

**Comment by KochTobi** [comment]
There is no easy way to do this so it works with the HA proxy setup.
