### ISSUE TITLE
Enable update of user account email address

### ISSUE THREAD

**Issue by FraBarSol** [qbicsoftware/data-manager-app#751]
I have some cases, where the End-Users E-mail has changed either because they got married (women sometimes take the family name of the husband) or because they changed affiliation.  This change affects the project management because it breaks communication and also makes difficult the invoice submission.  

It would be very useful if the end user is allow to update his/her E-mail and affiliation in their profile and that the Project managers can visualize the updated information.

**Comment by sven1103** [comment]
@FraBarSol however, we do not yet support affiliations, hence we do not consider it in this issue.
