### ISSUE TITLE
Evaluate technical feasability of TIB terminology service integration for ontology terms

### ISSUE THREAD

**Issue by sven1103** [qbicsoftware/data-manager-app#784]
### What are you missing?

Our terminology terms, e.g. for mass spec devices (see #734) need to be updated regularly to support recently added terms. However, the maintenance effort is moderate, and in case of #734 also frustrating, when file formats of ontologies suddenly break. 

At the same time, the availability of recent terms is a requirement of our service portfolio. If we cannot hold the promise, why are we enforcing ontology terms in the first place.

### Why do you need a solution?

I would like to evaluate the[ TIB terminology service API](https://terminology.tib.eu/ts/) and the technical feasibility of integration, especially with Vaadin's lazy loading data provider feature.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sven1103** [comment]
Ok, given that the both the Query class in Vaadin and the TIB terminology service API support page size (or rows), limit and offset (page). 
The response times are fast (<50ms), and with the filtering for provided ontologies, i think we should give it a try.

**Comment by sven1103** [comment]
- [ ] Define a terminology service
- [ ] Define a terminology repository interface, masking the implementation details of the HTTP REST API interaction and result object conversion
- [ ] Implement terminology repository
- [ ] Exchange ontology service for specimen, analyte and measurement device

**Comment by Shraddha0903** [comment]
UI Suggestion for the pre-selection of categories before the search:

![Ontology Search with Preselect-2](https://github.com/user-attachments/assets/4cd996bd-245a-461d-91ca-2e3a414a2801)
![Ontology Search with Preselect- empty state 2](https://github.com/user-attachments/assets/6ef499dc-df68-43d5-b936-c74bb4d8d78a)
