### ISSUE TITLE
Provide a run id for NGS measurement metadata

### ISSUE THREAD

**Issue by oquendoM** [qbicsoftware/data-manager-app#787]
### What are you missing?

Add the upload date to the downloaded metadata.

### Why do you need a solution?

Sometimes users want to know which measurements were sequenced together (= uploaded together). This information is already depicted on the browser, but is not visible if you download the measurement metadata.

### Ideas

Ideally the column would show only the date and exclude the time (ex. show 2024-07-24, instead of 2024-07-24 09:56). This makes filtering in excel possible.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by oquendoM** [comment]
Hi,

The information is used to download only samples from a specific sequencing batch, which often correspond to the upload date from the lab. It is also important to know which samples are in which batch to look for sequencing batch effect during the analysis.

Best, Morgana

**Comment by sven1103** [comment]
Hi @oquendoM , 

since we have the batch information, would it not make sense to have that information annotated upon measurement metadata export? We already provide the sample id and sample name, would just be another property.

What do you think?

Best, Sven

**Comment by oquendoM** [comment]
Unfortunately sequencing batch and delivered batch (this one normally matches the metadata submission by the user) does not always match. The upload date would still be more informative in my opinion. But the complain of the impossibility to easily match sample metadata to the "raw data" metadata is a complain I heard already from the qPortal. This is normally relevant for big projects (>100 samples).

**Comment by sven1103** [comment]
hm, but then I doubt the use of the batch property at all. We might need to differentiate between submission batch and measurement batch.

This can e.g. be realised, by providing an additional property for measurements. Like `Measurement Run` or sth alike?

**Comment by oquendoM** [comment]
Yes something like a `run ID`. Would this need to be added to the measurement metadata manually?

**Comment by sven1103** [comment]
> Would this need to be added to the measurement metadata manually?

yes, we would introduce a property for measurements :)
