### ISSUE TITLE
Display available data for registered measurements

### ISSUE THREAD

**Issue by sven1103** [qbicsoftware/data-manager-app#798]
### What are you missing?

A quick overview from the measurements, which of them already have registered data available.

### Why do you need a solution?

I would like to see, which measurements have already data ready for download, and also to get an feeling of security if all data has been registered for the registered measurements.

### Ideas

I think what can be super useful, is a gauge or sth similar to indicate how many datasets have been already registered for a dataset, and which measurements have raw data available.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Steffengreiner** [comment]
This can be investigated again after #705 is tackled
