### ISSUE TITLE
Think about a solution for components that should display empty state

### ISSUE THREAD

**Issue by sven1103** [qbicsoftware/data-manager-app#800]
### What are you missing?

The current implementation for displaying components that might have not yet information to display (empty state) is very heterogeneous in our application. For developer that want to extend, refactor components, this gets very messy and with every new component that comes, a new custom solution is created.

### Why do you need a solution?

Scalability of implementation!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by KochTobi** [comment]
What are the different cases of components?
Components with and without empty state?
What does an empty state entail? What kinds of empty states are there?
