### ISSUE TITLE
Update ontology list - NovaSeq X Series

### ISSUE THREAD

**Issue by oquendoM** [qbicsoftware/data-manager-app#807]
### What are you missing?

I am currently missing the ontology terms for NovaSeq X.

### Why do you need a solution?

So I can select this option as the instrument in the measurement metadata.

### Ideas

Update the ontology list. NovaSeq X and NovaSeq X Plus were added to EFO (EFO:0022840 and EFO:0022841) and OBI (https://github.com/obi-ontology/obi/issues/1802).

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sven1103** [comment]
Dear @oquendoM , 

thank your for reporting this. Missing ontology terms due to outdated ontology version support of the data manager will be addressed with the upcoming release next week.

The feature is already in the dev branch #784.

Best Sven
