### ISSUE TITLE
Improve the Project Summary view for better visualisation

### ISSUE THREAD

**Issue by Shraddha0903** [qbicsoftware/data-manager-app#812]
### What are you missing?

I am currently missing a better visualisation of the information that's important to the project.
I would need a UI pattern where we can show the project summary in a readable and intuitive manner.

### Why do you need a solution?

Currently the project summary view has a lot of information and not all of it is important to the user. The readability of this information also could be better.

### Ideas

Introduce an accordion, make use of labels and more visual indicators.

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by Shraddha0903** [comment]
UI Suggestions:

![Image](https://github.com/user-attachments/assets/f01decaa-27c4-4a35-a165-b61266a5a1a6)

There should be separate Edit dialogs for each section of the Project Summary, similar to the Project Creation dialog.

**Comment by sven1103** [comment]
Dear @Shraddha0903 , can you please list the Vaadin elements you have used for the UI refactor?  Makes the developer happy ;)
