### ISSUE TITLE
I'm unable to select the "sequencing read type" while registering or editing NGS measurements

### ISSUE THREAD

**Issue by Steffengreiner** [qbicsoftware/data-manager-app#823]
### What happened?

While registering NGS measurements i wanted to select the "Sequencing Read Type" for my samples from the preselected options. Sadly this was not possible, since the dropdown menu with possible options only appears after row 6

**No Dropdown** 
<img width="1439" alt="Screenshot 2024-09-03 at 17 33 52" src="https://github.com/user-attachments/assets/e1c2544a-90a0-471d-86a5-a977548b5d33">

**With Dropdown In Row 7**
<img width="1438" alt="Screenshot 2024-09-03 at 17 33 59" src="https://github.com/user-attachments/assets/a9a5021d-30af-44c5-8a15-7fbfddd36640">

Even worse i'm completely unable to see the possible selection options within the cells of the "Sequencing Read Type" column while editing the downloaded NGS measurements independent of the selected row. 

<img width="1440" alt="Screenshot 2024-09-03 at 17 36 02" src="https://github.com/user-attachments/assets/b50c248c-8d8c-4db0-b59a-a45c1da68398">

This occured in Excel and Numbers so i suspect it's on the application side. 

### What browsers are you seeing the problem on?

Excel and Numbers

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by KochTobi** [comment]
Still waiting for the edit case to be resolved.
