### ISSUE TITLE
Check for paired-end data

### ISSUE THREAD

**Issue by oquendoM** [qbicsoftware/data-manager-app#836]
### What are you missing?

A check to confirm if R1 and R2 FASTQ files are registered if the measurement metadata states the data is "PAIRED-END". Would this be possible?

### Why do you need a solution?

To avoid cases where only one of the reads is uploaded.

### Ideas

Maybe a flag on the measurement metadata if an uneven number of files is uploaded.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sven1103** [comment]
Dear @oquendoM , 

so you are worried that for paired end sequencing, on direction is missing?

**Comment by sven1103** [comment]
Currently, we dont have dataset validation and feedback for the data provider implemented. So for the moment, one would need to check the number of files for the raw data set tab in the application.

**Comment by oquendoM** [comment]
The worry is that for some reason (person forgot to add or problems during the upload) that read 1 or read 2 will be missing.

**Comment by sven1103** [comment]
I understand from a user perspective, however I am not yet sure if we have the capacity or time to do all these validations. The client that submits data has also responsibility and can implement measures on their side. 

Can we focus atm on transparency? I would like to carefully wait and evaluate use cases, when they come up. 

Upload issues must not happen and lead to an inconsistent state. That is what we need to make sure. Currently, it is not possible to register half of a dataset though, so I am not worried there.
