### ISSUE TITLE
Share and reference datasets that belong to an experiment

### ISSUE THREAD

**Issue by Shraddha0903** [qbicsoftware/data-manager-app#838]
### What are you missing?

A visualisation of how the results datasets of an experiment would look and how the user can interact with it.

### Why do you need a solution?

To enable the users to download their project results datasets and complete the data management project lifecycle.

### Ideas

The Results page would be integrated with the FDAT repository.
The user would need to first add their FDAT account on this page and then be able to view their datasets.

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by sven1103** [comment]
I also add the current draft of the process flow (Thanks to https://sequencediagram.org/!!)

[External_dataset_integration(2).txt](https://github.com/user-attachments/files/17144921/External_dataset_integration.2.txt)

![External_dataset_integration (3)](https://github.com/user-attachments/assets/188de748-fe36-4611-832b-38572d4ac965)

**Comment by Shraddha0903** [comment]
**Figma prototypes of use cases for result data integration in DM:**

1. Link a dataset to your project in the Data Manager 
https://www.figma.com/design/G0wNwsfyuYMwlSfqLjvsod/Data-Manager-App-Design?node-id=2165-24902&t=SgOhLzduXlDX0LSa-1

2. Check for availability of datasets in the Data Manager 
https://www.figma.com/design/G0wNwsfyuYMwlSfqLjvsod/Data-Manager-App-Design?node-id=235-3625&t=SgOhLzduXlDX0LSa-1

**Comment by Steffengreiner** [comment]
Superseded by https://github.com/qbicsoftware/data-manager-app/issues/1466
