### ISSUE TITLE
The link to newly registered samples sent over email is not correct

### ISSUE THREAD

**Issue by KochTobi** [qbicsoftware/data-manager-app#936]
### What happened?

After registering samples, I receive an email with an incorrect link to those samples.
1. register samples
2. receive email
3. click on link in email
4. see 404

### Relevant log output

```shell
Received link over email: 
https://rdm.qbic.uni-tuebingen.de/projects/84dc7b31-a7fd-4ab1-ae64-7b6ddc67a58f/samples

Working expected link:
https://rdm.qbic.uni-tuebingen.de/projects/84dc7b31-a7fd-4ab1-ae64-7b6ddc67a58f/experiments/00a2572b-dd71-4412-a3c6-9a27734588b6/samples
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Steffengreiner** [comment]
Heya @KochTobi, thanks you for making us aware of this issue and also helping solve it in the latest Release. Details can be found in the linked [PR](https://github.com/qbicsoftware/data-manager-app/pull/954)
